### ISSUE TITLE
The version hash of the download file url seems to have changed

### ISSUE THREAD

**Issue by Rin-Wood** [LostImbecile/DB-Legends-Sound-Extraction-Tool#3]
AssetBundleCatalog:https://nah3ohdioj7ye3sh.dblgnds.channel.or.jp/clientdata/f92bd96585f9993b79a432c63ba491c6c9fd5593/a/d58fc57a87e080bd1a6a62572165050c43f7ba38
assets:
https://nah3ohdioj7ye3sh.dblgnds.channel.or.jp/clientdata/fa00d41d8428de8993ff4f18d5b18a471e909d03/a/d6132923a4cedc1ac3089b5da1dc95d231bf10c7

**Comment by LostImbecile** [comment]
Thanks a lot for your help and the suggested solution you have sent me, the fix is in commit 50931e4
